services:
  backend:
    build: ./backend
    env_file:
      - ../secrets/.env
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./frontend:/frontend   # main.py が ../frontend (=/frontend) を参照するためマウント
    environment:
      - PYTHONUNBUFFERED=1
  iperf3-server:
    image: networkstatic/iperf3
    command: -s
    ports:
      - "5201:5201"
    container_name: iperf3-server

  dummy-web:
    image: nginx:latest
    container_name: dummy-web
    ports:
      - "8080:80"

networks:
  default:
    name: cui-learning-network
